CREATE DATABASE cpp_library;
CREATE USER cpp_user WITH PASSWORD 'secure_password';
GRANT CONNECT ON DATABASE cpp_library TO cpp_user;

\c cpp_library

GRANT USAGE ON SCHEMA public TO cpp_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO cpp_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cpp_user;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO cpp_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO cpp_user;