CREATE DATABASE omnedia;
CREATE USER omnedia_user WITH PASSWORD 'secure_password';
GRANT CONNECT ON DATABASE omnedia TO omnedia_user;

\c omnedia

GRANT USAGE ON SCHEMA public TO omnedia_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO omnedia_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO omnedia_user;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO omnedia_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO omnedia_user;